//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.27 at 07:15:48 PM CST 
//


package com.model.site;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.model.site package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Login_QNAME = new QName("http://www.example.org/site/", "login");
    private final static QName _NewElement_QNAME = new QName("http://www.example.org/site/", "NewElement");
    private final static QName _Refer_QNAME = new QName("http://www.example.org/site/", "refer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.model.site
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Refer }
     * 
     */
    public Refer createRefer() {
        return new Refer();
    }

    /**
     * Create an instance of {@link SourceSite }
     * 
     */
    public SourceSite createSourceSite() {
        return new SourceSite();
    }

    /**
     * Create an instance of {@link Httpclient }
     * 
     */
    public Httpclient createHttpclient() {
        return new Httpclient();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/site/", name = "login")
    public JAXBElement<String> createLogin(String value) {
        return new JAXBElement<String>(_Login_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Refer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/site/", name = "NewElement")
    public JAXBElement<Refer> createNewElement(Refer value) {
        return new JAXBElement<Refer>(_NewElement_QNAME, Refer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Refer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/site/", name = "refer")
    public JAXBElement<Refer> createRefer(Refer value) {
        return new JAXBElement<Refer>(_Refer_QNAME, Refer.class, null, value);
    }

}
