//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.27 at 07:15:48 PM CST 
//


package com.model.site;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for source_site complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="source_site">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="login" type="{http://www.example.org/site/}login" minOccurs="0"/>
 *         &lt;element name="refer" type="{http://www.example.org/site/}refer" minOccurs="0"/>
 *         &lt;element name="httpclient" type="{http://www.example.org/site/}httpclient" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="interval" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="depth" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="thread_num" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "source_site", propOrder = {
    "login",
    "refer",
    "httpclient"
})
public class SourceSite {

    protected Login login;
    protected Refer refer;
    protected Httpclient httpclient;
    @XmlAttribute(name = "interval")
    protected String interval;
    @XmlAttribute(name = "depth")
    protected Integer depth;
    @XmlAttribute(name = "thread_num")
    protected Integer threadNum;
    @XmlAttribute(name = "url")
    protected String url;

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link Login }
     *     
     */
    public Login getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link Login }
     *     
     */
    public void setLogin(Login value) {
        this.login = value;
    }

    /**
     * Gets the value of the refer property.
     * 
     * @return
     *     possible object is
     *     {@link Refer }
     *     
     */
    public Refer getRefer() {
        return refer;
    }

    /**
     * Sets the value of the refer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Refer }
     *     
     */
    public void setRefer(Refer value) {
        this.refer = value;
    }

    /**
     * Gets the value of the httpclient property.
     * 
     * @return
     *     possible object is
     *     {@link Httpclient }
     *     
     */
    public Httpclient getHttpclient() {
        return httpclient;
    }

    /**
     * Sets the value of the httpclient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Httpclient }
     *     
     */
    public void setHttpclient(Httpclient value) {
        this.httpclient = value;
    }

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterval(String value) {
        this.interval = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDepth(Integer value) {
        this.depth = value;
    }

    /**
     * Gets the value of the threadNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getThreadNum() {
        return threadNum;
    }

    /**
     * Sets the value of the threadNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setThreadNum(Integer value) {
        this.threadNum = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

}
