//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-661 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.05 at 10:00:53 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/demo/")
package com.processor.model;
